import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import type { AdminDashboardResponse } from '../types';
import { Users, Database, FileSpreadsheet, Activity, TrendingUp, ShieldAlert, Loader2 } from 'lucide-react';
import KPICard from '../components/KPICard';
import ChartsWrapper from '../components/charts/ChartsWrapper';

export default function AdminDashboard() {
  const [data, setData] = useState<AdminDashboardResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchDashboard = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.getAdminDashboard();
      setData(res);
    } catch (err: any) {
      setError(err.message || 'Failed to load admin statistics.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDashboard();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-[calc(100vh-80px)]">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="h-8 w-8 text-indigo-500 animate-spin" />
          <p className="text-sm text-slate-400 font-semibold">Loading administrative indices...</p>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="p-8 max-w-xl mx-auto my-12 glass-panel rounded-xl border border-rose-500/10 text-center space-y-4">
        <ShieldAlert className="h-10 w-10 text-rose-400 mx-auto" />
        <h3 className="font-bold text-slate-100">Access or Connection Error</h3>
        <p className="text-sm text-slate-400">{error}</p>
        <button
          onClick={fetchDashboard}
          className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold border border-slate-700 transition"
        >
          Retry Load
        </button>
      </div>
    );
  }

  const { metrics, client_growth, client_usage, recent_activity } = data;

  return (
    <div className="p-8 space-y-8 overflow-y-auto h-[calc(100vh-80px)]">
      {/* Platform Overview Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold text-slate-100 tracking-tight">Platform Overview</h2>
          <p className="text-xs text-slate-400">Manage tenants, datasets, usage logs, and system scaling indicators</p>
        </div>
      </div>

      {/* KPI Indicators */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <KPICard
          title="Total Clients"
          value={metrics.total_clients.toString()}
          icon={Users}
          description={`${metrics.active_clients} Active | ${metrics.suspended_clients} Suspended`}
          color="indigo"
        />
        <KPICard
          title="Total Datasets"
          value={metrics.total_datasets.toString()}
          icon={Database}
          description="Tenant uploaded data files"
          color="emerald"
        />
        <KPICard
          title="AI Queries Executed"
          value={metrics.total_analyses.toString()}
          icon={Activity}
          description="Insights generated by AI Engine"
          color="sky"
        />
        <KPICard
          title="Reports Generated"
          value={metrics.reports_generated.toString()}
          icon={FileSpreadsheet}
          description="Tenant formatted reports"
          color="amber"
        />
      </div>

      {/* Charts & Analytics */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Client Growth Chart */}
        <div className="glass-panel p-6 rounded-xl border border-slate-800 lg:col-span-2 space-y-4">
          <div>
            <h3 className="text-sm font-bold text-slate-200 tracking-wide uppercase">Client Growth Curve</h3>
            <span className="text-[10px] text-slate-500 font-medium">Tenant acquisition trends</span>
          </div>
          <ChartsWrapper
            chartType="line"
            xAxis="date"
            yAxis="clients"
            data={client_growth}
            height={260}
          />
        </div>

        {/* Recent Platform Activity */}
        <div className="glass-panel p-6 rounded-xl border border-slate-800 space-y-4">
          <div>
            <h3 className="text-sm font-bold text-slate-200 tracking-wide uppercase">Recent Activity</h3>
            <span className="text-[10px] text-slate-500 font-medium">Global platform action logs</span>
          </div>
          <div className="space-y-4 max-h-[260px] overflow-y-auto pr-1">
            {recent_activity.length === 0 ? (
              <p className="text-xs text-slate-500 text-center py-12">No recent platform activities logged</p>
            ) : (
              recent_activity.map((act, index) => (
                <div key={index} className="flex flex-col gap-1 p-3 rounded-lg bg-slate-900/30 border border-slate-800/40">
                  <div className="flex justify-between items-center text-[10px]">
                    <span className="font-semibold text-indigo-400">{act.client}</span>
                    <span className="text-slate-500">{act.timestamp}</span>
                  </div>
                  <p className="text-xs text-slate-300 font-medium">{act.event}</p>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Client Usage Matrix */}
      <div className="glass-panel p-6 rounded-xl border border-slate-800 space-y-4">
        <div>
          <h3 className="text-sm font-bold text-slate-200 tracking-wide uppercase">Client Usage Statistics</h3>
          <span className="text-[10px] text-slate-500 font-medium">Resource consumption metrics per client</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400 text-[10px] font-semibold tracking-wider uppercase">
                <th className="pb-3 pl-4">Company</th>
                <th className="pb-3 text-center">Datasets Uploaded</th>
                <th className="pb-3 text-center">AI Analyst Queries</th>
                <th className="pb-3 text-center">Reports Saved</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/50 text-xs font-semibold text-slate-300">
              {client_usage.map((usage, idx) => (
                <tr key={idx} className="hover:bg-slate-800/20">
                  <td className="py-4 pl-4 font-bold text-slate-200">{usage.company}</td>
                  <td className="py-4 text-center text-slate-400">{usage.datasets}</td>
                  <td className="py-4 text-center text-slate-400">{usage.queries}</td>
                  <td className="py-4 text-center text-slate-400">{usage.reports}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
